config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :categories
  resources :collections
  resources :pages
  mount Avo::Engine, at: Avo.configuration.root_path
  root 'home#index'
  resources :projects
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :collections, dependent: :destroy
  has_many :projects, :through => :collections

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/collection.rb
class Collection < ApplicationRecord
  # has_one :collection
  belongs_to :category
  has_many :projects

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :project

  def project_name=
    project&.name
  end
  alias_method :project_name, :project_name=
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_items
  # alias_attribute :name, :machine_name
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  scope :published, -> { where(is_public: true) }
  enum controller_name: { Category.name.pluralize.humanize => 'categories',
                           Collection.name.pluralize.humanize => "collections",
                           I18n.t('home') => "home",
                           Project.name.pluralize.humanize => "projects",
                           Page.name.pluralize.humanize => 'pages' }
  enum controller_action: { I18n.t('index') => 'index', I18n.t('show') => 'show' }

  # Generate the sequence no if not already provided.
  before_validation(on: :create) do
    items = MenuItem.where(menu_id: self.menu_id).order(:position)
    self.position = items.any? ? items.last.position + 1 : 0  unless self.position
  end

  def resource_link
    if linked_resource.present?
      name = linked_resource.try(:name) || linked_resource.try(:title)
      identifiant = linked_resource.try(:slug) || linked_resource.try(:id)
      "<a style='color:#fff;text-decoration:underline;' href=/avo/resources/#{self.controller_name.downcase}/#{identifiant}/edit>(#{self.controller_name.singularize}) #{ name }</a>".html_safe if name
    end
  end

  def linked_resource
    self.controller_name.singularize.constantize.find(self.resource_identifiant) if self.controller_name && self.resource_identifiant
  end

  def menu_name
    menu&.name
  end

  after_save :reorganize_position_index
  after_destroy :reorganize_position_index

  private

  def reorganize_position_index
    menu_items = MenuItem.where(menu_id: self.menu_id).order(:position)
    if menu_items.where(position: self.position).count > 1
      menu_items_to_rearrange = menu_items.where('position >= ?', self.position).where.not(id: self.id).to_a
      rearrange_collection(menu_items_to_rearrange, index: self.position + 1)
      menu_items.reload
    end

    rearrange_collection(menu_items.order(:position), index: 0) if menu_items.any? && (menu_items.last.position > (menu_items.count + 1) || menu_items.first.position > 0)
  end

  def rearrange_collection(collection, index: nil)
    collection.each { |x| x.update_columns(position: index) ; index = index + 1 }
  end
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image
  # has_one_attached :video
  has_one_attached :preview
  has_one_attached :hq_large_image

  belongs_to :collection
  has_one :category, :through => :collection

  has_many :links

  before_save :reset_url

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged


  scope :published, -> { where(is_public: true) }

  def category_name=
    category&.name
  end
  alias_method :category_name, :category_name=

  def collection_name=
    collection&.name
  end
  alias_method :collection_name, :collection_name=

  private
  def slug_candidates
    [
      :name,
      [:collection_name, :name],
      [:category_name, :collection_name, :name],
    ]
  end

  def reset_url
    self.slug = nil if self.name_changed?
  end


end

app/models/website_config.rb
class WebsiteConfig < ApplicationRecord
  has_one_attached :logo
  has_one_attached :banner

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @projects = @categories.map { |x| x.projects.published }.flatten.sort_by { |x| x.created_at }
    @page_title = Category.model_name.human&.pluralize
  end

  # GET /categories/1 or /categories/1.json
  def show
    @projects = @category.projects.published.order(created_at: :desc)
    @page_title = @category.name
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.published.order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  before_action :ensure_is_public, only: %i[ show ]

  # GET /categories or /categories.json
  def index
    @pages = Page.published
    # @projects = @categories.map { |x| x.projects.published }.flatten.sort_by { |x| x.created_at }
    @page_title = Page.model_name.human&.pluralize
  end

  # GET /categories/1 or /categories/1.json
  def show
    @page_title = @page.title
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.friendly.find(params[:id])
  end

  def ensure_is_public
    return redirect_to(root_path, status: 401) unless @page.is_public
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :body, :is_public)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :ensure_is_public, only: %i[ show ]

  # GET /projects or /projects.json
  def index
    @projects = Project.published.order(created_at: :desc)
    @page_title = Project.model_name.human&.pluralize

  end

  # GET /projects/1 or /projects/1.json
  def show
    @page_title = @project.name

    @crumbs = [@project.category, @project.collection]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    def ensure_is_public
      return redirect_to(root_path, status: 401) unless @project.is_public
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/avo/partials/_header.html.erb
<%= link_to $website_config&.website_name.presence || t('site_title'), '/', class: 'text-green-600 font-semibold' %>

app/views/avo/partials/_profile_dropdown.html.erb
<div <% if main_app.respond_to?(:destroy_admin_session_path) %> data-controller="toggle-panel" <% end %>>
  <a href="javascript:void(0);" class="flex items-center cursor-pointer font-semibold text-gray-700" data-action="click->toggle-panel#togglePanel">
    <% if _current_user.respond_to?(:avatar) &&  _current_user.avatar.present? %>
      <%= image_tag _current_user.avatar, class: "h-12 rounded-full border-4 border-white mr-1" %>
    <% end %>
    <% if _current_user.respond_to?(:name) && _current_user.name.present? %>
      <%== t('admin.hello', name: _current_user.name) %>
    <% elsif _current_user.respond_to?(:email) && _current_user.email.present? %>
      <%= _current_user.email %>
    <% else %>
      Avo user
    <% end %>
    <% if main_app.respond_to?(:destroy_admin_session_path) %>
      <%= svg 'chevron-down', class: "ml-1 h-4" %>
    <% end %>
  </a>

  <% if main_app.respond_to?(:destroy_admin_session_path) %>
    <div class="hidden absolute inset-auto inset-auto right-0 mr-6 mt-0 py-4 bg-white rounded-xl min-w-[200px] shadow-context" data-toggle-panel-target="panel">
      <%= button_to "Sign out", main_app.destroy_admin_session_path, method: :delete, form: { "data-turbo" => "false" }, class: "appearance-none bg-white text-left cursor-pointer text-green-600 font-semibold hover:text-white hover:bg-green-500 block px-4 py-1 w-full" %>
    </div>
  <% end %>
</div>

app/views/avo/sidebar/_sidebar.html.erb
<div class="application-sidebar flex h-full bg-white text-white w-56 z-50 border-r border-gray-300">
  <div class="flex flex-col w-full">
    <%= link_to root_path, class: 'logo-placeholder h-16 bg-white p-2 flex justify-center' do %>
      <%= render partial: "avo/partials/logo" %>
    <% end %>

    <div class="flex-1 flex flex-col justify-between">
      <div class="tools py-4">
        <%= render Avo::NavigationLinkComponent.new label: 'Get started', path: avo.root_path, active: :exclusive if Rails.env.development? && Avo.configuration.home_path.nil?  %>

        <%= render Avo::NavigationHeadingComponent.new label: t('avo.resources') %>

        <div class="w-full">
          <% routes_obj = Avo::Engine.routes %>
          <% resources = Avo::App.resources_navigation(_current_user) %>
          <% resources = resources.sort_by { |x| x.try(:custom_meta_data) ? x.custom_meta_data[:position] : 0 } %>
          <% resources.each do |resource| %>
            <% meta_data = resource.try(:custom_meta_data)  %>

            <% path_for_params = { action: :index, controller: "avo/#{ resource.model_class.name.underscore.pluralize.downcase }"  } %>
            <% path_for_params.merge!({action: :edit, id: meta_data[:direct_access_to] }) if meta_data && meta_data[:direct_access_to].present? %>

            <%= render Avo::NavigationHeadingComponent.new label: meta_data[:title_before] if meta_data && meta_data[:title_before].present? %>

            <%= render Avo::NavigationLinkComponent.new label: resource.plural_name.humanize, path: routes_obj.path_for(path_for_params) %>
            <%= "<hr>".html_safe if meta_data && meta_data[:hr_after] %>
          <% end %>

          <% sidebar_partials = Avo::App.get_sidebar_partials %>
          <% if sidebar_partials.present? %>
            <%= render Avo::NavigationHeadingComponent.new label: t('avo.tools') %>

            <% sidebar_partials.each do |partial| %>
              <%= render partial: "/avo/sidebar/items/#{partial}" %>
            <% end %>
          <% end %>
        </div>

      </div>

      <%= render_license_warnings %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="main-menu">
  <%= render 'shared/menu', machine_name: :main_menu %>
  <%= render 'shared/projects_menu' unless controller_name == 'home' || controller_name == 'sessions' %>
</header>

app/views/shared/_menu.html.erb
<% menu = Menu.find_by(machine_name: machine_name) rescue nil %>
<% menu_items = menu.present? ? menu.menu_items.published : [] %>
<% if menu_items.any? %>
  <ul class="menu-container">
    <% menu_items.each do |menu_item| %>
      <%# next if menu_item %>
      <% options = { controller: menu_item.controller_name_before_type_cast, action: menu_item.controller_action_before_type_cast, only_path: true } %>
      <% if menu_item.controller_action_before_type_cast == "show" && menu_item.resource_identifiant  %>
        <% slug = menu_item.linked_resource %>
        <% options[:id] = slug %>
      <% end %>
      <%= content_tag(:li, link_to(menu_item.name, Rails.application.routes.url_helpers.url_for(options))) %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_projects_menu.html.erb
<div class="project-menu">
  <%# render 'shared/menu', machine_name: :sidebar_menu %>
  <% collections = Collection.all.group_by { |x| x.category_id } %>
  <% if collections.any? %>
    <ul class="menu-container">
      <% collections.each do |category_id, collections_array| %>
        <% category = Category.find category_id %>
        <li><%= link_to category.name, category_path(category) %></li>
        <ul>
          <% collections_array.each do |collection| %>
            <li><%= link_to collection.name, collection_path(collection) %></li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_projects_slider.html.erb
<% if model_collection.any? %>
  <div class="projects-slider">
    <div class="glide">
      <div class="glide__track" data-glide-el="track">
        <ul class="glide__slides">
          <% model_collection.each do |object| %>
            <li class="glide__slide" data-project-title="<%= object.name %>" data-project-url="<%= project_url(object) %>">
              <%# link_to object.name, '#' %>
              <%= image_tag object.image&.url %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="glide-bullets-container">
        <h1>
          <% first_project = model_collection.first %>
          <%= link_to project_url(first_project) do  %>
            <span><%= first_project.name %></span>
            <%# image_tag 'projects-eye-sign.png' %>
          <% end %>
        </h1>
        <div class="glide__bullets" data-glide-el="controls[nav]">
          <% model_collection.each_with_index do |object, index| %>
            <% url = object.preview.attached? ? object.preview.url : object.image&.url %>
            <% next unless url %>
            <div class="glide__bullet" data-glide-dir="=<%= index %>">
              <%= image_tag url %>
            </div>
          <% end %>
        </div>

      </div>

    </div>
  </div>
<% end %>

app/views/shared/old/_artist_name.html.erb
<div class="artist-name">
  <%= $website_config.artist_name %>
</div>

app/views/shared/old/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/old/_main_menu.html.erb
<div class="sidebar-navigation">
    <%= Menu.name.humanize %>
</div>

<div class="sidebar-info">
  <div class="sidebar-navigation-modal">
    <%= render 'shared/menu_parts/navigation' %>
  </div>

  <div class="sidebar-main-title">
    <%= render 'shared/menu_parts/website_name' %>
  </div>

  <div class="sidebar-logo">
    <%= render 'shared/menu_parts/logo' %>
  </div>

  <% name = @name.presence || @page_title %>
  <% if @crumbs || name %>
    <div class="sidebar-project-collection">
      <%= render 'shared/menu_parts/breadcrumbs', crumbs: @crumbs if @crumbs %>
      <%= render 'shared/menu_parts/resource_name', name: name  %>
    </div>
  <% end %>

  <% if @project %>
    <%= render 'shared/menu_parts/project_details' %>
  <% elsif params[:controller] != 'home' %>
    <div class="sidebar-collections">
      <%# render 'shared/menu_parts/category_navigation' %>
      <%= render 'shared/menu_parts/collections_navigation', collection: ( @category.try(:collections) || Collection.all) unless @collection %>
      <%= render 'shared/menu_parts/collections_navigation', collection: Category.all unless @category %>
    </div>
  <% end %>
</div>

app/views/shared/old/_project_item.html.erb
<div class="project-item">
  <div class="project-image">
    <%= link_to image_tag(project.image), project_url(project) %>
  </div>
</div>

app/views/shared/old/_projects.html.erb
<% model_collection.each do |project| %>
  <% next unless project.image.present? %>
  <%= render 'shared/project_item', project: project %>
<% end %>

app/views/shared/old/menu_parts/_breadcrumbs.html.erb
<div class="sidebar-collection-name">
  <% crumbs.each do |crumb| %>
    <%= link_to crumb.name, url_for(controller: crumb.class.name.pluralize.underscore, action: 'show', id: crumb.slug) %>
    <%= " > " unless crumb == crumbs.last %>
  <% end %>
</div>

app/views/shared/old/menu_parts/_collections_navigation.html.erb
<% if collection.any? %>
  <% model =  collection.first
                        .class.name
                        .pluralize %>
  <h2><%= model.humanize %></h2>
  <ul>
    <% collection.each do |category| %>
      <%= content_tag(:li, link_to(category.name, url_for(controller: model.underscore, action: 'show', id: category.slug))) rescue next %>
    <% end %>
  </ul>
<% end %>

app/views/shared/old/menu_parts/_logo.html.erb
<%= link_to image_tag($website_config.logo, width: 100), root_url %>

app/views/shared/old/menu_parts/_navigation.html.erb
<% menu = Menu.find_by(machine_name: :main_menu) %>
<% menu_items = menu.present? ? menu.menu_items.published : [] %>
<div class="menu-container">
  <% if menu_items.any? %>
    <ul>
      <% menu_items.each do |menu_item| %>
        <%# next if menu_item %>
        <% options = { controller: menu_item.controller_name_before_type_cast, action: menu_item.controller_action_before_type_cast } %>
        <% if menu_item.controller_action_before_type_cast == "show" && menu_item.resource_identifiant  %>
          <% slug = menu_item.linked_resource %>
          <% options[:id] = slug %>
        <% end %>
        <%= content_tag(:li, link_to(menu_item.name, url_for(options))) %>
      <% end %>
    </ul>
    <%= render 'shared/menu_parts/collections_navigation', collection: Category.all %>
    <%= render 'shared/menu_parts/collections_navigation', collection: Collection.all %>
  <% end %>
</div>

app/views/shared/old/menu_parts/_project_details.html.erb
<% if @project.description.present? %>
  <div class="sidebar-project-description">
    <%== @project.description %>
  </div>
<% end %>

<% if $website_config.show_projects_links && @project.links.any? %>
  <div class="sidebar-project-urls">
    <h2><%= Link.name.pluralize.humanize %></h2>
    <% @project.links.each do |link|  %>
      <%= link_to link.name, link.url %>
      <%= " | " unless link == @project.links.last %>
    <% end  %>
  </div>
<% end %>

app/views/shared/old/menu_parts/_resource_name.html.erb
<div class="sidebar-project-name">
  <%= name %>
</div>

app/views/shared/old/menu_parts/_website_name.html.erb
<h1>
  <%= link_to $website_config&.website_name.presence || t('site_title'), root_url %>
</h1>